# ========================
# CONFIGURAZIONE GENERALE
# ========================
spring.application.name=libreria
server.port=8080

# ========================
# LOGGING
# ========================
# Log di livello INFO per tutta l'applicazione
logging.level.root=INFO
# Log di livello DEBUG solo per il nostro codice (utile in sviluppo)
logging.level.com.moscadanilo=DEBUG

# ========================
# PROFILO ATTIVO
# ========================
# spring.profiles.active=dev


# Database
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}