# ========================
# CONFIGURAZIONE GENERALE
# ========================
spring.application.name=libreria
server.port=8080

# ========================
# LOGGING
# ========================
# Log di livello INFO per tutta l'applicazione
logging.level.root=INFO
# Log di livello DEBUG solo per il nostro codice (utile in sviluppo)
logging.level.com.moscadanilo=DEBUG

# ========================
# PROFILO ATTIVO
# ========================
# spring.profiles.active=dev


# Database e credenziali
# URL per database
spring.datasource.url=${DB_URL}
# Credenziali
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# ── JPA / Hibernate ──────────────────────────────────────────────────────────
# Hibernate Properties
# Dialetto SQL da usare. The SQL dialect makes Hibernate generate better SQL for the chosen database 
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQLDialect

# ── Come si comporta il database all'avvio dell'applicazione ────
# DDL auto: crea le tabelle allo startup (drop-and-create ad ogni avvio)
# Valori possibili: none | validate | update | create | create-drop
spring.jpa.hibernate.ddl-auto=update

#! Impostazioni aggiuntive, utili per il testing (rimuoverle dopo)
# Mostra le query SQL generate da Hibernate nella console
spring.jpa.show-sql=true
# Formatta le query SQL per renderle leggibili
spring.jpa.properties.hibernate.format_sql=true

#Inizializza il data.sql in resources dopo l'avvio
# LA RIGA di SEGUITO E' DA ATTIVARE SOLO AL PRIMO RIAVVIO
spring.jpa.defer-datasource-initialization=true

# LA RIGA di SEGUITO E' DA ATTIVARE SOLO AL PRIMO RIAVVIO
spring.sql.init.mode=always
# LA RIGA di SEGUITO E' DA ATTIVARE SOLO AL PRIMO RIAVVIO
spring.sql.init.data-locations=classpath:data.sql